services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data
    # ports: ["5432:5432"] # сыртқа ашу керек болса ғана

  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env               # Барлық құпия/айнымалылар осында
    environment:
      MIX_ENV: dev
      PHX_SERVER: "true"               # тек қосымша параметрлер осында
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"
    ports:
      - "4010:4000"

volumes:
  dbdata:
