
services:
  db:
    image: postgres:16
    container_name: lms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_dev || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    # (қалауыңыз бойынша) локалдан psql қосылу үшін:
    # ports:
    #   - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_web
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      MIX_ENV: "dev"
      PHX_SERVER: "true"
      PHX_HOST: "localhost"
      PORT: "4000"

      # DB env — Repo конфигімен сәйкестендірілді
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "lms_dev"

      # Қаласаңыз, Ecto URL-ды да береміз (Repo url: ... қолданса)
      DATABASE_URL: "ecto://postgres:postgres@db:5432/lms_dev"

      # Dev үшін default мәндер (егер .env жоқ болса)
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-dev-secret-please-change}"
      LIVE_VIEW_SIGNING_SALT: "${LIVE_VIEW_SIGNING_SALT:-devsalt}"
    ports:
      - "4001:4000"
    volumes:
      - ./:/app
      - deps:/app/deps
      - build:/app/_build
      - node_modules:/app/assets/node_modules
    command: >
      sh -lc "
        mix deps.get &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "

volumes:
  pgdata:
  deps:
  build:
  node_modules:
