services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lms_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_dev || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      PHX_HOST: "localhost"
      PORT: "4000"
      PHX_SERVER: "true"
      MIX_ENV: "dev"
      DATABASE_URL: "ecto://postgres:postgres@db:5432/lms_dev"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      LIVE_VIEW_SIGNING_SALT: "${LIVE_VIEW_SIGNING_SALT}"
    command: sh -lc "mix ecto.migrate && mix phx.server"

volumes:
  pgdata:
